# Generated by Django 3.2.9 on 2021-11-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.role')),
            ],
            options={
                'db_table': 'master',
            },
        ),
    ]
