# Generated by Django 3.2.9 on 2021-11-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.course')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.master')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.master')),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
