# Generated by Django 3.2.9 on 2021-12-04 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_auto_20211128_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Dob',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Gender',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='Dob',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(default='', max_length=15),
        ),
    ]
